#%RAML 1.0 NamedExample
          [{
        "id": 100,
        "customer_id": 22,
        "driver_id": 403,
        "unit_price": 411.0,
        },
        {
        "id": 101,  
        "customer_id": 23,
        "driver_id": 403,
        "unit_price": 855.0
          }
          ]
          