#%RAML 1.0 NamedExample
         {
            "Name": "Abebe beso bela", 
            "Address": "123 abc white house",
            "Email": "Abebe_Bela@Ethio.com",
            "Phone Number": 025568478
            
          }