#%RAML 1.0 NamedExample
DeliveryManexample:              {
                "Name": "Yidnekachew Maru",
                "Location": "GroupB",
                "Phone number": 2469780561           
              }